NEGATIVE_APPRAISALS: dict[str, str] = {
    "Self-Blame":           "The event happened because of the way I acted",
    "Self-Doubt":           "I can't trust that I will do the right thing",
    "Weakness Belief":      "I am a weak person",
    "Fear of Rage":         "I will not be able to control my anger and will do something terrible",
    "Low Coping":           "I can't deal with even the slightest upset",
    "Lost Happiness":       "I used to be a happy person but now I am always miserable.",
    "Mistrust":             "People can't be trusted",
    "Hypervigilance":       "I have to be on guard all the time",
    "Emotional Numbness":   "I feel dead inside",
    "Fear of Harm":         "You can never know who will harm you",
    "Constant Vigilance":   "I have to be especially careful because you never know what can happen next",
    "Inadequacy":           "I am inadequate",
    "Thought Avoidance":    "If I think about the event, I will not be able to handle it",
    "Character Blame":      "The event happened to me because of the sort of person I am",
    "Fear Going Crazy":     "My reactions since the event mean that I am going crazy",
    "Lost Emotions":        "I will never be able to feel normal emotions again",
    "World is Dangerous":   "The world is a dangerous place",
    "Others-Would-Cope":    "Somebody else would have stopped the event from happening",
    "Permanent Damage":     "I have permanently changed for the worse",
    "Dehumanization":       "I feel like an object, not like a person",
    "Self-Comparison":      "Somebody else would not have gotten into this situation",
    "Can't Rely on Others": "I can't rely on other people",
    "Isolation":            "I feel isolated and set apart from others",
    "Hopelessness":         "I have no future",
    "Helplessness":         "I can't stop bad things from happening to me",
    "Distrust Others":      "People are not what they seem",
    "Life Destroyed":       "My life has been destroyed by the trauma",
    "Defective Self":       "There is something wrong with me as a person",
    "Bad Coper":            "My reactions since the event show that I am a lousy coper",
    "Intrinsic Fault":      "There is something about me that made the event happen",
    "Identity Loss":        "I feel like I don't know myself anymore",
    "Can't Rely on Self":   "I can't rely on myself",
    "No Good Ahead":        "Nothing good can happen to me anymore",
}

DISTRACTION_STRATEGIES: dict[str, str] = {
    "Thought Suppression":    "I try to push them out of my mind",
    "Memory Erasure":         "I try to erase the memory of the event",
    "Emotion Control":        "I try hard to control my emotions",
    "Distraction":            "I distract myself with something else",
    "Redirection":            "I think of something else",
    "Busyness":               "I work hard at keeping busy with other things",
    "Sexual Coping":          "I release my tension with sexual fantasies/ activities",
    "Counterfactual Thinking": "I think about how life would have been different if the event had not occurred",
    "Prevention Rumination":  "I dwell on how the event could have been prevented",
    "Meaning Seeking":        "I think about why the event has happened to me",
    "Past Dwelling":          "I dwell on how I used to be before the event",
    "Other-Blame Rumination": "I dwell on what other people have done to me",
    "Self-Blame Rumination":  "I dwell on what I have done wrong",
    "Downward Comparison":    "I remind myself it could have been worse",
    "Emotional Numbing":      "I numb my feelings",
    "Memory Detachment":      "I detach myself from the memories",
    "Dissociation":           "I pretend it happened to someone else",
    "Fantasy Escape":         "I drift off into a world of my own",
    "Substance Use":          "I drink alcohol, take medication or use drugs",
    "Smoking":                "I smoke",
    "Sensory Distraction":    "I put on loud music or TV",
}

AVOIDANCE_STRATEGIES: dict[str, str] = {
    "Avoid Talking":          "Talking with others about the event or its aftermath",
    "Avoid Reminders":        "Being reminded of the event by others",
    "Avoid Similar People":   "Seeing other people that were involved in the event or that look similar",
    "Avoid Social Contacts":  "Seeing people that I socialised with before the event",
    "Avoid Thinking":         "Thinking about the event",
    "Avoid Media":            "Watching TV programmes/ films or reading about similar events",
    "Avoid Location":         "Going to or near the place where the event happened",
    "Avoid Circumstances":    "Being in circumstances that remind me of the event (eg, being in the dark).",
    "Avoid Medical Cues":     "Hospitals/ Ambulances/ Physical Examinations",
    "Avoid Police":           "Police",
    "Avoid Exercise":         "Exercise",
    "Avoid Sex":              "Sex",
    "Avoid Going Out":        "Going out",
    "Avoid Physical Stress":  "Situations that put my body under stress",
    "Avoid Emotional Stress": "Situations that make me feel strong emotions",
    "Avoid Evaluation":       "Situations in which other people evaluate me / my appearance / my performance",
}

TRIGGERS: dict[str, str] = {
    # Sensory
    "Olfactory (Alcohol)":          "Alcohol smell",
    "Olfactory Danger Cue":         "Burnt smell",
    "Auditory (Babies)":            "Babies",
    "Auditory (Cars)":              "Car sounds",
    "Auditory/Threat":              "Gunshot noise",
    "Auditory (Children Crying)":   "Kids crying",
    "Auditory (Loud Noises)":       "Loud noises",
    "Auditory/Mechanical":          "Motorcycle noise",
    "Auditory (Sirens)":            "Sirens",
    "Auditory (Language)":          "Shouting in Arabic",
    "Auditory (Language Confusion)": "Uncomprehinsible chatter",
    "Auditory (Voice)":             "Related voice",
    "Auditory (Sounds)":            "Related sounds",
    "Olfactory (Smell)":            "Related smells",
    "Visual (Photos)":              "Related photos",
    "Visual/Bodily Cues":           "Blood",
    "Tactile (Unexpected Touch)":   "Being touched unprepared",
    "Tactile (Touch)":              "Physical touch",
    "Cold Temperature":             "Cold",
    "Somatic Pain (Neck)":          "Neck pain",
    # Situational
    "Animals":                      "Dogs",
    "Emergency Contexts":           "Ambulances",
    "Transportation (Bicycle)":     "Bicycle",
    "Public Transport":             "Bus riding",
    "Crash Imagery":                "Cars hit by accident",
    "Car Similarity":               "Similar cars",
    "Driving with Others":          "Driving with people",
    "Media Exposure":               "Related media content",
    "Media / News":                 "Related news",
    "Workplace":                    "Workplace",
    "Military Topics":              "Talks about military",
    "Animal Phobia":                "Talks or photos about snakes",
    "Sexual Trauma Cues":           "Comments on sexual violence",
    "Violence":                     "Violence",
    "Old Memories":                 "Old photos",
    "Perceived Threat":             "People acting suspiciously",
    "Others Cycling":               "People cycling",
    # Environmental
    "Authority Presence":           "Police",
    "Authority Figures":            "People in uniform",
    "Spatial Triggers":             "Physical locations",
    "Proximity":                    "Physical proximity",
    "Crowding":                     "Crowded places",
    "Crowding/Overstimulation":     "Crowded spaces",
    "Darkness":                     "Dark spaces",
    "Ethnic/Geographic Tension":    "Arab villages",
    # Interpersonal
    "Moral Violation":              "People misbehaving",
    "Male Presence":                "Being alone with men",
    "Sexual Objectification":       "Being looked at sexually",
    "Family-Related Comments":      "Comments on family",
    "Conflict":                     "Confrontations",
    "Shouting":                     "Shouting",
    "Arguments":                    "Arguments",
    "Stranger Interaction":         "Talking to strangers",
    "Idealized Families":           "Happy families",
    "Known People":                 "Related people",
    "Event Involvement":            "People who are related to the event",
    "Victim Similarity":            "People who look similar to the victims",
    "Relationship Reminders":       "When people say things like my ex",
    # Trauma-Related
    "Offender Cues":                "Seeing the offender",
    "Event Recall":                 "Talking about the event",
    "Crash Discussions":            "Talk about accidents",
    "Loss Themes":                  "Talk about people loosing loved ones",
    "Name Reminders":               "Hearing related names",
    "Victim Memories":              "Reminders of victims",
    "Trauma-Related Events":        "Trauma-related events",
    "Certain Songs":                "Certain songs",
    "Certain Conversation Topics":  "Certain conversation topics",
    # Perceptual / Emotional
    "Loss of Autonomy":             "Being forced to do something",
    "Vulnerability":                "Being naked",
    "Self-Consciousness":           "Being seen",
    "Entrapment":                   "Having no options",
    "Loss of Control":              "Lack of control",
    "Discomfort":                   "Feeling uncomfortable",
    "Positive Emotion Confusion":   "Positive emotions",
    "Future Orientation":           "Talking about the future",
    "Uncertainty":                  "Uncertainty",
    "Unpredictability":             "Unpredictable situations",
    "Intrusive Thoughts":           "Unwanted thoughts",
    "Stress":                       "Stress",
    "Affective Expression":         "Crying",
    "Object Throwing":              "Object throwing",
}

THREAT: dict[str, str] = {
    "Flashbacks":          "Suddenly feeling or acting as if the stressful experience were actually happening again",
    "Physical Reactivity": "Having strong physical reactions when something reminded you of the stressful experience",
    "Negative Emotions":   "Having strong negative feelings such as fear, horror, anger, guilt, or shame",
    "Irritability":        "Irritable behavior, angry outbursts, or acting aggressively",
    "Risky Behavior":      "Taking too many risks or doing things that could cause you harm",
    "Hypervigilance":      "Being superalert or watchful or on guard",
    "Startle Response":    "Feeling jumpy or easily startled",
    "Concentration":       "Having difficulty concentrating",
    "Sleep Problems":      "Trouble falling or staying asleep",
}

MEMORY: dict[str, str] = {
    "Visual Memories":      "My memories of the frightening event are mostly pictures or images.",
    "Nonverbal Memory":     "I can't seem to put the frightening event into words.",
    "Auditory Recall":      "When I have memories of what happened I sometimes hear things in my head that I heard during the frightening event.",
    "Reliving Event":       "When I remember the frightening event I feel like it is happening right now.",
    "Olfactory Recall":     "When I think about the frightening event I can sometimes smell things that I smelt when the frightening event happened.",
    "Verbal Access":        "I can talk about what happened very easily.",
    "Snapshot Memory":      "I remember the frightening event as a few moments, and each moment is a picture in my mind.",
    "Memory Replay":        "My memories of the frightening event are like a film that plays over and over.",
    "Vivid Memory":         "My memories of the frightening event are very clear and detailed.",
    "Photographic Recall":  "Remembering what happened during the frightening event is just like looking at photographs of it in my mind.",
    "Bodily Reenactment":   "When memories come to mind of what happened, I feel my body is in the same position as when the frightening event occurred.",
}

MALADAPTIVE_STRATEGIES: dict[str, str] = {
    "Suppress Thoughts":            "try hard not think about the trauma",
    "Mental Distraction":           "keep mind occupied all the time",
    "Emotion Control":              "control feelings",
    "Alcohol Use":                  "drink alcohol",
    "Drug Use":                     "take drugs",
    "Emotional Numbing":            "numb emotions",
    "Avoid All Feelings":           "avoid anything that could cause negative or positive feelings",
    "Rumination: Prevention":       "ruminate about how event could have been prevented",
    "Rumination: Revenge":          "ruminate about how to get even with assailant",
    "Avoid Event Site":             "avoid site of the event",
    "Avoid Similar Clothes":        "avoid wearing similar clothes",
    "Carry Weapon":                 "carry weapon",
    "Hypervigilance towards people": "vigilant for dangerous people",
    "Avoid Crowds":                 "avoid crowded places",
    "Stay Near Exit":               "make sure to stay close to exit",
    "Mirror Checking":              "keep checking mirrors",
    "Avoid Future Plans":           "do not make any plans for the future",
    "Avoid Friends":                "avoid seeing friends",
    "Stop Enjoyment":               "give up pleasant activities",
    "Avoid People":                 "avoid other people",
    "Face Hiding":                  "cover face with hands",
    "Heavy Makeup":                 "heavy make-up",
    "Avoid Eye Contact":            "look down",
    "Delay Sleep":                  "stay up until very late",
    "Avoid Stressors":              "avoid anything that could be stressful",
}
